#pragma once

namespace Editor
{
	enum class LEVEL { STATIC, EDIT, SHADER, ANIMATION, EFFECT, MAP, UI, CAMERA, STATEMACHINE, SFX, END };
	enum class CHANNEL { BGM, PLAYER_ACTION, PLAYER_VOICE, ENEMY_ACTION, ENEMY_VOICE, EFFECT, END };

	enum class SHADER_ANIMPATH { DEFAULT_NORMAL, NORMAL_TEXTURE, SHADOW, END };

	enum class COLLISIONLAYER { NONE, PLAYER, CHARACTER, CAMERA, ATTACK, SKILL, ENEMY, ENEMY_ATTACK, ENEMY_SKILL, INTERACTION, DETECT, PARRY, GRAB, MAP, END };
	enum class OBJECTTYPE { DEFAULT, SONORA, INTERACTION, SPAWNOR, DESTRUCTION, NONRIGID, TRIGGERBOX, NONSONORA, NONSONORA_FLOOR, METEO, WATER, COLLAPS, END };

	enum class WEAPONTYPE { NONANIM, ANIM, END };
}