#pragma once

namespace Editor
{
	enum class LEVEL { STATIC, EDIT, SHADER, ANIMATION, EFFECT, MAP, UI, END };
	enum class CHANNEL { BGM, PLAYER_ACTION, PLAYER_VOICE, ENEMY_ACTION, ENEMY_VOICE, EFFECT, END };
	enum class COLLISIONLAYER { PLAYER, CHARACTER, ATTACK, SKILL, ENEMY, ENEMY_ATTACK, ENEMY_SKILL, INTERACTION, DETECT, PARRY, GRAB, END };
	enum class SHADER_ANIMPATH { DEFAULT_NORMAL, NORMAL_TEXTURE, SHADOW, END};
}